apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: complete-devops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/tanishaaritonang/end-to-end-devOps/tree/master'
    targetRevision: HEAD
    path: complete-devops-project-time-printer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  